### ISSUE TITLE
CAR5-Agregar Historia de Usuario

### ISSUE THREAD

**Issue by ISBACsolzac** [ricardo77a/itz_tutorias_msc#33]
Agregar historia de usuario de eliminar ya que no se encuentra registrada, y validar ya que tiene 2 historias de usuario que realizan lo mismo listar y ver

**Comment by Gennysis** [comment]
He creado la Historia de Usuario y valide, Listar es cuando muestra todas las carreras dadas de alta y ver muestra el registro seleccionado
