### ISSUE TITLE
ALU4 - Boton guardar manda error 404

### ISSUE THREAD

**Issue by pakosamuel** [ricardo77a/itz_tutorias_msc#39]
El botón guardar al hacerle click arroja un error 404 
![Captura](https://user-images.githubusercontent.com/47428264/54067677-55502c80-4208-11e9-8730-85907a283a2a.PNG)

**Comment by pakosamuel** [comment]
![Captura](https://user-images.githubusercontent.com/47428264/54067672-44072000-4208-11e9-81a0-ce7fafad8468.PNG)

**Comment by jncsoga** [comment]
Se cambio el botón por Cancelar y no ejecuta la acción de Save

![image](https://user-images.githubusercontent.com/9665267/54079870-bdefe580-42aa-11e9-83a3-1239cbe5ca78.png)
