### ISSUE TITLE
PRE 3 - VERIFICAR RADIOS

### ISSUE THREAD

**Issue by ricardo77a** [ricardo77a/itz_tutorias_msc#56]
Los radios siempre muestran "Activa" como seleccionada

![image](https://user-images.githubusercontent.com/24514193/54074922-53b15380-425e-11e9-8e8f-d0a7b72d7b14.png)
![image](https://user-images.githubusercontent.com/24514193/54074925-5d3abb80-425e-11e9-9a93-cb697f4bf2e5.png)

**Comment by pakosamuel** [comment]
se desactivo el checked de Activo y ahora no muestra ninguna seleccionada
