### ISSUE TITLE
PRE 4 - Estado Radio

### ISSUE THREAD

**Issue by ricardo77a** [ricardo77a/itz_tutorias_msc#58]
El estado siempre se muestra como activo
![image](https://user-images.githubusercontent.com/24514193/54074946-86f3e280-425e-11e9-98b3-0e71bf8726cd.png)
![image](https://user-images.githubusercontent.com/24514193/54074950-8fe4b400-425e-11e9-8952-8537e94b7c54.png)

**Comment by pakosamuel** [comment]
se corrigió
