### ISSUE TITLE
SEG1 - Github mandar mensaje amigable

### ISSUE THREAD

**Issue by jncsoga** [ricardo77a/itz_tutorias_msc#67]
![image](https://user-images.githubusercontent.com/9665267/54076852-b82bdd00-4275-11e9-96be-e3ce7d447a76.png)

Debe de mandar un mensaje amigable informando de que el correo ya esta en uso

**Comment by jncsoga** [comment]
No esta llenando el campo name, y esta como requerido en base de datos

**Comment by ricardo77a** [comment]
Corregido, cuando presionas el botón, registra o loggea.
