### ISSUE TITLE
SEG2 - No se validan campos requeridos para llenar el formulario

### ISSUE THREAD

**Issue by jncsoga** [ricardo77a/itz_tutorias_msc#69]
No se están validando campos requeridos en el formulario de registro de usuario

![image](https://user-images.githubusercontent.com/9665267/54076940-0a213280-4277-11e9-940a-434eb2981cbd.png)

**Comment by ricardo77a** [comment]
Se agregó el siguiente código 
`if (is_null($user->name)) {`
`$user->name = $user->email;`
`}`

Si no tiene name usará el correo electrónico
